<?xml version="1.0" encoding="UTF-8"?>
<!--
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
-->
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
                      http://maven.apache.org/xsd/maven-4.0.0.xsd">

  <parent>
    <groupId>org.apache.impala</groupId>
    <artifactId>impala-parent</artifactId>
    <version>4.5.0-RELEASE</version>
    <relativePath>../../pom.xml</relativePath>
  </parent>
  <modelVersion>4.0.0</modelVersion>
  <artifactId>impala-minimal-s3a-aws-sdk</artifactId>
  <packaging>jar</packaging>

  <properties>
    <aws.sdk.v2.version>2.35.4</aws.sdk.v2.version>
  </properties>

  <dependencies>
    <dependency>
      <groupId>org.apache.hadoop</groupId>
      <artifactId>hadoop-aws</artifactId>
      <version>${hadoop.version}</version>
      <exclusions>
        <exclusion>
          <groupId>software.amazon.awssdk</groupId>
          <artifactId>bundle</artifactId>
        </exclusion>
        <exclusion>
          <groupId>com.amazonaws</groupId>
          <artifactId>aws-java-sdk-bundle</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>software.amazon.awssdk</groupId>
      <artifactId>bundle</artifactId>
      <version>${aws.sdk.v2.version}</version>
    </dependency>
  </dependencies>
  <build>
    <plugins>
      <plugin>
        <artifactId>maven-shade-plugin</artifactId>
        <version>3.5.1</version>
        <configuration>
          <artifactSet>
            <includes>
              <include>software.amazon.awssdk:bundle</include>
            </includes>
          </artifactSet>
          <filters>
            <filter>
              <artifact>software.amazon.awssdk:bundle</artifact>
              <excludes>
                <exclude>software/amazon/awssdk/services/accessanalyzer/**</exclude>
                <exclude>software/amazon/awssdk/services/account/**</exclude>
                <exclude>software/amazon/awssdk/services/acm/**</exclude>
                <exclude>software/amazon/awssdk/services/acmpca/**</exclude>
                <exclude>software/amazon/awssdk/services/amplify/**</exclude>
                <exclude>software/amazon/awssdk/services/amplifybackend/**</exclude>
                <exclude>software/amazon/awssdk/services/amplifyuibuilder/**</exclude>
                <exclude>software/amazon/awssdk/services/apigateway/**</exclude>
                <exclude>software/amazon/awssdk/services/apigatewaymanagementapi/**</exclude>
                <exclude>software/amazon/awssdk/services/apigatewayv2/**</exclude>
                <exclude>software/amazon/awssdk/services/appconfig/**</exclude>
                <exclude>software/amazon/awssdk/services/appconfigdata/**</exclude>
                <exclude>software/amazon/awssdk/services/appflow/**</exclude>
                <exclude>software/amazon/awssdk/services/applicationautoscaling/**</exclude>
                <exclude>software/amazon/awssdk/services/applicationdiscovery/**</exclude>
                <exclude>software/amazon/awssdk/services/applicationinsights/**</exclude>
                <exclude>software/amazon/awssdk/services/appmesh/**</exclude>
                <exclude>software/amazon/awssdk/services/apprunner/**</exclude>
                <exclude>software/amazon/awssdk/services/appstream/**</exclude>
                <exclude>software/amazon/awssdk/services/appsync/**</exclude>
                <exclude>software/amazon/awssdk/services/athena/**</exclude>
                <exclude>software/amazon/awssdk/services/auditmanager/**</exclude>
                <exclude>software/amazon/awssdk/services/autoscaling/**</exclude>
                <exclude>software/amazon/awssdk/services/autoscalingplans/**</exclude>
                <exclude>software/amazon/awssdk/services/backup/**</exclude>
                <exclude>software/amazon/awssdk/services/backupgateway/**</exclude>
                <exclude>software/amazon/awssdk/services/batch/**</exclude>
                <exclude>software/amazon/awssdk/services/braket/**</exclude>
                <exclude>software/amazon/awssdk/services/chime/**</exclude>
                <exclude>software/amazon/awssdk/services/chimesdkidentity/**</exclude>
                <exclude>software/amazon/awssdk/services/chimesdkmediapipelines/**</exclude>
                <exclude>software/amazon/awssdk/services/chimesdkmeetings/**</exclude>
                <exclude>software/amazon/awssdk/services/chimesdkmessaging/**</exclude>
                <exclude>software/amazon/awssdk/services/cloud9/**</exclude>
                <exclude>software/amazon/awssdk/services/cloudcontrol/**</exclude>
                <exclude>software/amazon/awssdk/services/clouddirectory/**</exclude>
                <exclude>software/amazon/awssdk/services/cloudformation/**</exclude>
                <exclude>software/amazon/awssdk/services/cloudfront/**</exclude>
                <exclude>software/amazon/awssdk/services/cloudhsm/**</exclude>
                <exclude>software/amazon/awssdk/services/cloudhsmv2/**</exclude>
                <exclude>software/amazon/awssdk/services/cloudsearch/**</exclude>
                <exclude>software/amazon/awssdk/services/cloudsearchdomain/**</exclude>
                <exclude>software/amazon/awssdk/services/cloudtrail/**</exclude>
                <exclude>software/amazon/awssdk/services/cloudwatch/**</exclude>
                <exclude>software/amazon/awssdk/services/cloudwatchevents/**</exclude>
                <exclude>software/amazon/awssdk/services/cloudwatchlogs/**</exclude>
                <exclude>software/amazon/awssdk/services/codeartifact/**</exclude>
                <exclude>software/amazon/awssdk/services/codebuild/**</exclude>
                <exclude>software/amazon/awssdk/services/codecommit/**</exclude>
                <exclude>software/amazon/awssdk/services/codedeploy/**</exclude>
                <exclude>software/amazon/awssdk/services/codeguruprofiler/**</exclude>
                <exclude>software/amazon/awssdk/services/codegurureviewer/**</exclude>
                <exclude>software/amazon/awssdk/services/codepipeline/**</exclude>
                <exclude>software/amazon/awssdk/services/codestar/**</exclude>
                <exclude>software/amazon/awssdk/services/codestarconnections/**</exclude>
                <exclude>software/amazon/awssdk/services/codestarnotifications/**</exclude>
                <exclude>software/amazon/awssdk/services/cognitoidentity/**</exclude>
                <exclude>software/amazon/awssdk/services/cognitoidentityprovider/**</exclude>
                <exclude>software/amazon/awssdk/services/cognitosync/**</exclude>
                <exclude>software/amazon/awssdk/services/comprehend/**</exclude>
                <exclude>software/amazon/awssdk/services/comprehendmedical/**</exclude>
                <exclude>software/amazon/awssdk/services/computeoptimizer/**</exclude>
                <exclude>software/amazon/awssdk/services/config/**</exclude>
                <exclude>software/amazon/awssdk/services/connect/**</exclude>
                <exclude>software/amazon/awssdk/services/connectcampaigns/**</exclude>
                <exclude>software/amazon/awssdk/services/connectcases/**</exclude>
                <exclude>software/amazon/awssdk/services/connectcontactlens/**</exclude>
                <exclude>software/amazon/awssdk/services/connectparticipant/**</exclude>
                <exclude>software/amazon/awssdk/services/costandusagereport/**</exclude>
                <exclude>software/amazon/awssdk/services/costexplorer/**</exclude>
                <exclude>software/amazon/awssdk/services/customerprofiles/**</exclude>
                <exclude>software/amazon/awssdk/services/databasemigration/**</exclude>
                <exclude>software/amazon/awssdk/services/databrew/**</exclude>
                <exclude>software/amazon/awssdk/services/dataexchange/**</exclude>
                <exclude>software/amazon/awssdk/services/datapipeline/**</exclude>
                <exclude>software/amazon/awssdk/services/datasync/**</exclude>
                <exclude>software/amazon/awssdk/services/dax/**</exclude>
                <exclude>software/amazon/awssdk/services/detective/**</exclude>
                <exclude>software/amazon/awssdk/services/devicefarm/**</exclude>
                <exclude>software/amazon/awssdk/services/devopsguru/**</exclude>
                <exclude>software/amazon/awssdk/services/directconnect/**</exclude>
                <exclude>software/amazon/awssdk/services/directory/**</exclude>
                <exclude>software/amazon/awssdk/services/dlm/**</exclude>
                <exclude>software/amazon/awssdk/services/docdb/**</exclude>
                <exclude>software/amazon/awssdk/services/drs/**</exclude>
                <exclude>software/amazon/awssdk/services/dynamodb/**</exclude>
                <exclude>software/amazon/awssdk/services/dynamodbstreams/**</exclude>
                <exclude>software/amazon/awssdk/services/ebs/**</exclude>
                <exclude>software/amazon/awssdk/services/ec2/**</exclude>
                <exclude>software/amazon/awssdk/services/ec2instanceconnect/**</exclude>
                <exclude>software/amazon/awssdk/services/ecr/**</exclude>
                <exclude>software/amazon/awssdk/services/ecrpublic/**</exclude>
                <exclude>software/amazon/awssdk/services/ecs/**</exclude>
                <exclude>software/amazon/awssdk/services/efs/**</exclude>
                <exclude>software/amazon/awssdk/services/eks/**</exclude>
                <exclude>software/amazon/awssdk/services/elasticache/**</exclude>
                <exclude>software/amazon/awssdk/services/elasticbeanstalk/**</exclude>
                <exclude>software/amazon/awssdk/services/elasticinference/**</exclude>
                <exclude>software/amazon/awssdk/services/elasticloadbalancing/**</exclude>
                <exclude>software/amazon/awssdk/services/elasticloadbalancingv2/**</exclude>
                <exclude>software/amazon/awssdk/services/elasticsearch/**</exclude>
                <exclude>software/amazon/awssdk/services/elastictranscoder/**</exclude>
                <exclude>software/amazon/awssdk/services/emr/**</exclude>
                <exclude>software/amazon/awssdk/services/emrcontainers/**</exclude>
                <exclude>software/amazon/awssdk/services/emrserverless/**</exclude>
                <exclude>software/amazon/awssdk/services/eventbridge/**</exclude>
                <exclude>software/amazon/awssdk/services/evidently/**</exclude>
                <exclude>software/amazon/awssdk/services/finspace/**</exclude>
                <exclude>software/amazon/awssdk/services/finspacedata/**</exclude>
                <exclude>software/amazon/awssdk/services/firehose/**</exclude>
                <exclude>software/amazon/awssdk/services/fis/**</exclude>
                <exclude>software/amazon/awssdk/services/fms/**</exclude>
                <exclude>software/amazon/awssdk/services/forecast/**</exclude>
                <exclude>software/amazon/awssdk/services/forecastquery/**</exclude>
                <exclude>software/amazon/awssdk/services/frauddetector/**</exclude>
                <exclude>software/amazon/awssdk/services/fsx/**</exclude>
                <exclude>software/amazon/awssdk/services/gamelift/**</exclude>
                <exclude>software/amazon/awssdk/services/glacier/**</exclude>
                <exclude>software/amazon/awssdk/services/globalaccelerator/**</exclude>
                <exclude>software/amazon/awssdk/services/glue/**</exclude>
                <exclude>software/amazon/awssdk/services/grafana/**</exclude>
                <exclude>software/amazon/awssdk/services/greengrass/**</exclude>
                <exclude>software/amazon/awssdk/services/greengrassv2/**</exclude>
                <exclude>software/amazon/awssdk/services/groundstation/**</exclude>
                <exclude>software/amazon/awssdk/services/guardduty/**</exclude>
                <exclude>software/amazon/awssdk/services/health/**</exclude>
                <exclude>software/amazon/awssdk/services/healthlake/**</exclude>
                <exclude>software/amazon/awssdk/services/honeycode/**</exclude>
                <exclude>software/amazon/awssdk/services/iam/**</exclude>
                <exclude>software/amazon/awssdk/services/identitystore/**</exclude>
                <exclude>software/amazon/awssdk/services/imagebuilder/**</exclude>
                <exclude>software/amazon/awssdk/services/inspector/**</exclude>
                <exclude>software/amazon/awssdk/services/inspector2/**</exclude>
                <exclude>software/amazon/awssdk/services/iot/**</exclude>
                <exclude>software/amazon/awssdk/services/iot1clickdevices/**</exclude>
                <exclude>software/amazon/awssdk/services/iot1clickprojects/**</exclude>
                <exclude>software/amazon/awssdk/services/iotanalytics/**</exclude>
                <exclude>software/amazon/awssdk/services/iotdataplane/**</exclude>
                <exclude>software/amazon/awssdk/services/iotdeviceadvisor/**</exclude>
                <exclude>software/amazon/awssdk/services/iotevents/**</exclude>
                <exclude>software/amazon/awssdk/services/ioteventsdata/**</exclude>
                <exclude>software/amazon/awssdk/services/iotfleethub/**</exclude>
                <exclude>software/amazon/awssdk/services/iotjobsdataplane/**</exclude>
                <exclude>software/amazon/awssdk/services/iotsecuretunneling/**</exclude>
                <exclude>software/amazon/awssdk/services/iotsitewise/**</exclude>
                <exclude>software/amazon/awssdk/services/iotthingsgraph/**</exclude>
                <exclude>software/amazon/awssdk/services/iottwinmaker/**</exclude>
                <exclude>software/amazon/awssdk/services/iotwireless/**</exclude>
                <exclude>software/amazon/awssdk/services/ivs/**</exclude>
                <exclude>software/amazon/awssdk/services/ivschat/**</exclude>
                <exclude>software/amazon/awssdk/services/kafka/**</exclude>
                <exclude>software/amazon/awssdk/services/kafkaconnect/**</exclude>
                <exclude>software/amazon/awssdk/services/kendra/**</exclude>
                <exclude>software/amazon/awssdk/services/keyspaces/**</exclude>
                <exclude>software/amazon/awssdk/services/kinesis/**</exclude>
                <exclude>software/amazon/awssdk/services/kinesisanalytics/**</exclude>
                <exclude>software/amazon/awssdk/services/kinesisanalyticsv2/**</exclude>
                <exclude>software/amazon/awssdk/services/kinesisvideo/**</exclude>
                <exclude>software/amazon/awssdk/services/kinesisvideoarchivedmedia/**</exclude>
                <exclude>software/amazon/awssdk/services/kinesisvideomedia/**</exclude>
                <exclude>software/amazon/awssdk/services/kinesisvideosignaling/**</exclude>
                <exclude>software/amazon/awssdk/services/lakeformation/**</exclude>
                <exclude>software/amazon/awssdk/services/lambda/**</exclude>
                <exclude>software/amazon/awssdk/services/lexmodelbuilding/**</exclude>
                <exclude>software/amazon/awssdk/services/lexmodelsv2/**</exclude>
                <exclude>software/amazon/awssdk/services/lexruntime/**</exclude>
                <exclude>software/amazon/awssdk/services/lexruntimev2/**</exclude>
                <exclude>software/amazon/awssdk/services/licensemanager/**</exclude>
                <exclude>software/amazon/awssdk/services/lightsail/**</exclude>
                <exclude>software/amazon/awssdk/services/location/**</exclude>
                <exclude>software/amazon/awssdk/services/lookoutequipment/**</exclude>
                <exclude>software/amazon/awssdk/services/lookoutmetrics/**</exclude>
                <exclude>software/amazon/awssdk/services/lookoutvision/**</exclude>
                <exclude>software/amazon/awssdk/services/machinelearning/**</exclude>
                <exclude>software/amazon/awssdk/services/macie/**</exclude>
                <exclude>software/amazon/awssdk/services/macie2/**</exclude>
                <exclude>software/amazon/awssdk/services/managedblockchain/**</exclude>
                <exclude>software/amazon/awssdk/services/marketplacecatalog/**</exclude>
                <exclude>software/amazon/awssdk/services/marketplacecommerceanalytics/**</exclude>
                <exclude>software/amazon/awssdk/services/marketplaceentitlement/**</exclude>
                <exclude>software/amazon/awssdk/services/marketplacemetering/**</exclude>
                <exclude>software/amazon/awssdk/services/mediaconnect/**</exclude>
                <exclude>software/amazon/awssdk/services/mediaconvert/**</exclude>
                <exclude>software/amazon/awssdk/services/medialive/**</exclude>
                <exclude>software/amazon/awssdk/services/mediapackage/**</exclude>
                <exclude>software/amazon/awssdk/services/mediapackagevod/**</exclude>
                <exclude>software/amazon/awssdk/services/mediastore/**</exclude>
                <exclude>software/amazon/awssdk/services/mediastoredata/**</exclude>
                <exclude>software/amazon/awssdk/services/mediatailor/**</exclude>
                <exclude>software/amazon/awssdk/services/memorydb/**</exclude>
                <exclude>software/amazon/awssdk/services/mgn/**</exclude>
                <exclude>software/amazon/awssdk/services/migrationhub/**</exclude>
                <exclude>software/amazon/awssdk/services/migrationhubconfig/**</exclude>
                <exclude>software/amazon/awssdk/services/migrationhubrefactorspaces/**</exclude>
                <exclude>software/amazon/awssdk/services/migrationhubstrategy/**</exclude>
                <exclude>software/amazon/awssdk/services/mobile/**</exclude>
                <exclude>software/amazon/awssdk/services/mq/**</exclude>
                <exclude>software/amazon/awssdk/services/mturk/**</exclude>
                <exclude>software/amazon/awssdk/services/mwaa/**</exclude>
                <exclude>software/amazon/awssdk/services/neptune/**</exclude>
                <exclude>software/amazon/awssdk/services/networkfirewall/**</exclude>
                <exclude>software/amazon/awssdk/services/networkmanager/**</exclude>
                <exclude>software/amazon/awssdk/services/nimble/**</exclude>
                <exclude>software/amazon/awssdk/services/opensearch/**</exclude>
                <exclude>software/amazon/awssdk/services/opsworks/**</exclude>
                <exclude>software/amazon/awssdk/services/opsworkscm/**</exclude>
                <exclude>software/amazon/awssdk/services/organizations/**</exclude>
                <exclude>software/amazon/awssdk/services/outposts/**</exclude>
                <exclude>software/amazon/awssdk/services/panorama/**</exclude>
                <exclude>software/amazon/awssdk/services/personalize/**</exclude>
                <exclude>software/amazon/awssdk/services/personalizeevents/**</exclude>
                <exclude>software/amazon/awssdk/services/personalizeruntime/**</exclude>
                <exclude>software/amazon/awssdk/services/pi/**</exclude>
                <exclude>software/amazon/awssdk/services/pinpoint/**</exclude>
                <exclude>software/amazon/awssdk/services/pinpointemail/**</exclude>
                <exclude>software/amazon/awssdk/services/pinpointsmsvoice/**</exclude>
                <exclude>software/amazon/awssdk/services/polly/**</exclude>
                <exclude>software/amazon/awssdk/services/pricing/**</exclude>
                <exclude>software/amazon/awssdk/services/proton/**</exclude>
                <exclude>software/amazon/awssdk/services/qldb/**</exclude>
                <exclude>software/amazon/awssdk/services/qldbsession/**</exclude>
                <exclude>software/amazon/awssdk/services/quicksight/**</exclude>
                <exclude>software/amazon/awssdk/services/ram/**</exclude>
                <exclude>software/amazon/awssdk/services/rbin/**</exclude>
                <exclude>software/amazon/awssdk/services/rds/**</exclude>
                <exclude>software/amazon/awssdk/services/rdsdata/**</exclude>
                <exclude>software/amazon/awssdk/services/redshift/**</exclude>
                <exclude>software/amazon/awssdk/services/redshiftdata/**</exclude>
                <exclude>software/amazon/awssdk/services/rekognition/**</exclude>
                <exclude>software/amazon/awssdk/services/resiliencehub/**</exclude>
                <exclude>software/amazon/awssdk/services/resourcegroups/**</exclude>
                <exclude>software/amazon/awssdk/services/resourcegroupstaggingapi/**</exclude>
                <exclude>software/amazon/awssdk/services/robomaker/**</exclude>
                <exclude>software/amazon/awssdk/services/rolesanywhere/**</exclude>
                <exclude>software/amazon/awssdk/services/route53/**</exclude>
                <exclude>software/amazon/awssdk/services/route53domains/**</exclude>
                <exclude>software/amazon/awssdk/services/route53recoverycluster/**</exclude>
                <exclude>software/amazon/awssdk/services/route53recoverycontrolconfig/**</exclude>
                <exclude>software/amazon/awssdk/services/route53recoveryreadiness/**</exclude>
                <exclude>software/amazon/awssdk/services/route53resolver/**</exclude>
                <exclude>software/amazon/awssdk/services/rum/**</exclude>
                <exclude>software/amazon/awssdk/services/s3control/**</exclude>
                <exclude>software/amazon/awssdk/services/s3outposts/**</exclude>
                <exclude>software/amazon/awssdk/services/sagemaker/**</exclude>
                <exclude>software/amazon/awssdk/services/sagemakera2iruntime/**</exclude>
                <exclude>software/amazon/awssdk/services/sagemakeredge/**</exclude>
                <exclude>software/amazon/awssdk/services/sagemakerfeaturestoreruntime/**</exclude>
                <exclude>software/amazon/awssdk/services/sagemakerruntime/**</exclude>
                <exclude>software/amazon/awssdk/services/savingsplans/**</exclude>
                <exclude>software/amazon/awssdk/services/schemas/**</exclude>
                <exclude>software/amazon/awssdk/services/secretsmanager/**</exclude>
                <exclude>software/amazon/awssdk/services/securityhub/**</exclude>
                <exclude>software/amazon/awssdk/services/serverlessapplicationrepository/**</exclude>
                <exclude>software/amazon/awssdk/services/servicecatalog/**</exclude>
                <exclude>software/amazon/awssdk/services/servicediscovery/**</exclude>
                <exclude>software/amazon/awssdk/services/servicequotas/**</exclude>
                <exclude>software/amazon/awssdk/services/ses/**</exclude>
                <exclude>software/amazon/awssdk/services/sesv2/**</exclude>
                <exclude>software/amazon/awssdk/services/sfn/**</exclude>
                <exclude>software/amazon/awssdk/services/shield/**</exclude>
                <exclude>software/amazon/awssdk/services/signer/**</exclude>
                <exclude>software/amazon/awssdk/services/sms/**</exclude>
                <exclude>software/amazon/awssdk/services/snowball/**</exclude>
                <exclude>software/amazon/awssdk/services/snowdevicemanagement/**</exclude>
                <exclude>software/amazon/awssdk/services/sns/**</exclude>
                <exclude>software/amazon/awssdk/services/sqs/**</exclude>
                <exclude>software/amazon/awssdk/services/ssm/**</exclude>
                <exclude>software/amazon/awssdk/services/ssmcontacts/**</exclude>
                <exclude>software/amazon/awssdk/services/ssmincidents/**</exclude>
                <exclude>software/amazon/awssdk/services/sso/**</exclude>
                <exclude>software/amazon/awssdk/services/ssoadmin/**</exclude>
                <exclude>software/amazon/awssdk/services/ssooidc/**</exclude>
                <exclude>software/amazon/awssdk/services/storagegateway/**</exclude>
                <exclude>software/amazon/awssdk/services/support/**</exclude>
                <exclude>software/amazon/awssdk/services/swf/**</exclude>
                <exclude>software/amazon/awssdk/services/synthetics/**</exclude>
                <exclude>software/amazon/awssdk/services/textract/**</exclude>
                <exclude>software/amazon/awssdk/services/timestreamquery/**</exclude>
                <exclude>software/amazon/awssdk/services/timestreamwrite/**</exclude>
                <exclude>software/amazon/awssdk/services/transcribe/**</exclude>
                <exclude>software/amazon/awssdk/services/transcribestreaming/**</exclude>
                <exclude>software/amazon/awssdk/services/transfer/**</exclude>
                <exclude>software/amazon/awssdk/services/translate/**</exclude>
                <exclude>software/amazon/awssdk/services/voiceid/**</exclude>
                <exclude>software/amazon/awssdk/services/waf/**</exclude>
                <exclude>software/amazon/awssdk/services/wafv2/**</exclude>
                <exclude>software/amazon/awssdk/services/wellarchitected/**</exclude>
                <exclude>software/amazon/awssdk/services/wisdom/**</exclude>
                <exclude>software/amazon/awssdk/services/workdocs/**</exclude>
                <exclude>software/amazon/awssdk/services/worklink/**</exclude>
                <exclude>software/amazon/awssdk/services/workmail/**</exclude>
                <exclude>software/amazon/awssdk/services/workmailmessageflow/**</exclude>
                <exclude>software/amazon/awssdk/services/workspaces/**</exclude>
                <exclude>software/amazon/awssdk/services/workspacesweb/**</exclude>
                <exclude>software/amazon/awssdk/services/xray/**</exclude>
              </excludes>
            </filter>
          </filters>
        </configuration>
        <executions>
          <execution>
            <phase>package</phase>
            <goals>
              <goal>shade</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</project>
